// Local browser regression: durable drafts remain distinct from confirmed findings. No model calls.
const assert = require('node:assert/strict');
const { chromium } = require('playwright-core');
const base = process.env.COPILOT_URL || 'http://127.0.0.1:3000';
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/home/ryan/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome', headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  await page.route('**/api/**', (route) => { if (/health/.test(route.request().url())) return route.continue(); return route.abort(); });
  try {
    await page.goto(base);
    await page.getByLabel('Job label (optional)').fill('Draft regression');
    await page.getByRole('button', { name: 'Start job' }).click();
    await page.getByRole('heading', { name: 'What are we working on?' }).waitFor();
    const jobUrl = page.url();
    const jobId = jobUrl.split('/').pop();
    const readJob = () => page.evaluate((id) => new Promise((resolve, reject) => {
      const req = indexedDB.open('field-copilot');
      req.onsuccess = () => { const db = req.result; const get = db.transaction('jobs').objectStore('jobs').get(id); get.onsuccess = () => { resolve(get.result); db.close(); }; get.onerror = reject; };
      req.onerror = reject;
    }), jobId);
    await page.getByRole('link', { name: /Condenser/ }).click();
    await page.getByRole('link', { name: /Electrical readings/ }).click();
    await page.getByLabel('Line voltage (V)').waitFor();
    const toolUrl = page.url();
    await page.getByLabel('Nominal voltage (V)').fill('240');
    await page.getByLabel('Line voltage (V)').fill('238');
    await page.getByLabel('Recommended next step (optional)').fill('Repeat after review');
    await page.waitForTimeout(350);
    await page.reload();
    assert.equal(await page.getByLabel('Line voltage (V)').inputValue(), '238', 'unsaved measurement survives reload');
    assert.equal(await page.getByLabel('Recommended next step (optional)').inputValue(), 'Repeat after review', 'unsaved review survives reload');
    assert.equal((await readJob()).findings.length, 0, 'typing never confirms a finding');
    await page.getByRole('button', { name: 'Save finding' }).click();
    await page.getByRole('button', { name: 'Saved', exact: true }).waitFor();
    await page.waitForTimeout(350);
    assert.equal((await readJob()).drafts.length, 0, 'explicit confirmation clears draft');
    await page.getByLabel('Line voltage (V)').fill('230');
    await page.goto(jobUrl);
    await page.goto(toolUrl);
    assert.equal(await page.getByLabel('Line voltage (V)').inputValue(), '230', 'draft overrides old saved inputs after navigation');
    assert.equal((await readJob()).findings[0].readings.find((r) => r.label === 'Line voltage').value, 238, 'saved finding remains original');
    assert.deepEqual(errors, []);
    console.log('PASS draft form/review reload, no autosave findings, save clears drafts, edits survive navigation');
    await page.goto(`${jobUrl}/condenser/nameplate`);
    await page.getByLabel('Rated load amps', { exact: true }).fill('15');
    await page.getByRole('button', { name: 'Save equipment' }).click();
    await page.getByRole('button', { name: 'Saved', exact: true }).waitFor();
    await page.goto(`${jobUrl}/summary`);
    await page.getByText('Finding needs reconfirmation', { exact: true }).waitFor();
    const checkbox = page.locator("section[aria-label='System 1'] input[type=checkbox]").first();
    assert.equal(await checkbox.isDisabled(), true, 'stale evidence cannot be selected for a customer note');
    assert.equal(await page.getByRole('button', { name: 'Generate estimate note' }).isDisabled(), true);
    await page.goto(toolUrl);
    const reconfirm = page.getByRole('button', { name: 'Reconfirm finding' });
    assert.equal(await reconfirm.isDisabled(), true, 'stale evidence requires explicit review');
    await page.getByLabel('I reviewed the readings and references against the current nameplate.').check();
    assert.equal(await reconfirm.isDisabled(), false);
    await reconfirm.click();
    await page.getByRole('button', { name: 'Saved', exact: true }).waitFor();
    await page.waitForTimeout(350);
    const confirmed = await readJob();
    assert.equal(confirmed.findings[0].staleAt, undefined);
    assert.ok(confirmed.findingHistory[0].staleAt);
    assert.equal(confirmed.findingHistory[0].readings.find((r) => r.label === 'Line voltage').value, 238);
    console.log('PASS stale findings blocked from selection/AI, explicit review reconfirms and preserves history');
    await page.goto(`${jobUrl}/summary`);
    await page.getByRole('heading', { name: 'Finding history' }).waitFor();
    await page.locator("section[aria-label='System 1'] input[type=checkbox]").first().check();
    await page.getByLabel('Equipment age (years, optional)').fill('not a number');
    assert.equal(await page.getByRole('button', { name: 'Generate estimate note' }).isDisabled(), true, 'invalid age is not silently changed to unknown');
    await page.getByLabel('Equipment age (years, optional)').fill('');
    assert.equal(await page.getByRole('button', { name: 'Generate estimate note' }).isDisabled(), false);
    console.log('PASS invalid summary age blocks generation while blank remains unknown');
    await page.goto(jobUrl);
    await page.getByRole('link', { name: /Furnace or air handler/ }).click();
    await page.getByRole('link', { name: /^Airflow/ }).waitFor();
    const furnaceRoot = page.url();
    await page.getByRole('link', { name: /^Airflow/ }).click();
    await page.getByLabel('Method', { exact: true }).selectOption('flow-hood');
    await page.getByLabel(/System tonnage/).fill('3');
    await page.getByLabel(/Airflow reading 1/).fill('1200');
    await page.getByRole('button', { name: 'Add reading', exact: true }).click();
    await page.getByText('After readings and capacity (optional)', { exact: true }).click();
    await page.getByRole('button', { name: 'Add after reading', exact: true }).click();
    await page.reload();
    assert.equal(await page.getByLabel(/Airflow reading 1/).inputValue(), '1200');
    assert.equal(await page.getByLabel(/Airflow reading 2/).inputValue(), '');
    assert.equal(await page.getByLabel(/After reading 1/).count(), 1);
    await page.getByRole('button', { name: 'Save finding', exact: true }).click();
    await page.getByRole('button', { name: 'Saved', exact: true }).waitFor();
    await page.reload();
    assert.equal(await page.getByLabel(/Airflow reading 1/).inputValue(), '1200');
    assert.equal(await page.getByLabel(/Airflow reading 2/).inputValue(), '');
    await page.goto(`${furnaceRoot}/static`);
    await page.getByLabel(/Supply static/).fill('0.1');
    await page.getByLabel(/Return static/).fill('0.2');
    await page.getByLabel(/Rated external static/).fill('0.3');
    await page.getByRole('button', { name: 'Add component', exact: true }).click();
    await page.getByLabel('Component 1', { exact: true }).fill('Filter');
    await page.getByLabel(/^Drop/).fill('0.12');
    await page.reload();
    assert.equal(await page.getByLabel('Component 1', { exact: true }).inputValue(), 'Filter');
    assert.equal(await page.getByLabel(/^Drop/).inputValue(), '0.12');
    await page.getByRole('button', { name: 'Save finding', exact: true }).click();
    await page.getByRole('button', { name: 'Saved', exact: true }).waitFor();
    await page.reload();
    assert.equal(await page.getByLabel('Component 1', { exact: true }).inputValue(), 'Filter');
    assert.equal(await page.getByLabel(/^Drop/).inputValue(), '0.12');
    console.log('PASS blank multirow airflow and static component objects restored from drafts and saved findings');
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
