#!/usr/bin/env python3
"""Generates app/lib/charge/ptData.generated.ts from CoolProp.

PROVISIONAL DATA: values come from the CoolProp equations of state, not from a
manufacturer chart. R-454B is modeled as a mass-fraction mixture of R-32 and
R-1234yf with CoolProp's default interaction parameters. Compare against the
manufacturer's chart before trusting field decisions, then flip PT_DATA_APPROVED
in app/lib/charge/ptData.ts.

Usage: pip install CoolProp && python3 scripts/generate-pt-data.py
"""
import json
import os
from datetime import date

import CoolProp
from CoolProp.CoolProp import PropsSI

ATM_PA = 101325.0
PSI_PA = 6894.757293168


def f_from_k(k):
    return k * 9 / 5 - 459.67


# R-454B nominal composition 68.9 / 31.1 percent mass R-32 / R-1234yf, converted to mole fractions.
MW32, MW1234 = 52.024, 114.04
n32, n1234 = 68.9 / MW32, 31.1 / MW1234
x32 = n32 / (n32 + n1234)
R454B = f"HEOS::R32[{x32:.5f}]&R1234yf[{1 - x32:.5f}]"

FLUIDS = [
    # id, CoolProp name, ASHRAE class, max psig, step psig
    ("R-410A", "R410A", "A1", 620, 2),
    ("R-32", "R32", "A2L", 640, 2),
    ("R-454B", R454B, "A2L", 600, 2),
    ("R-22", "R22", "A1", 380, 1),
]

tables = []
for rid, name, cls, max_psig, step in FLUIDS:
    bubble, dew = [], []
    for psig in range(0, max_psig + 1, step):
        p_abs = ATM_PA + psig * PSI_PA
        try:
            bubble.append(round(f_from_k(PropsSI("T", "P", p_abs, "Q", 0, name)), 2))
            dew.append(round(f_from_k(PropsSI("T", "P", p_abs, "Q", 1, name)), 2))
        except Exception:
            break
    tables.append(
        {
            "id": rid,
            "safetyClass": cls,
            "startPsig": 0,
            "stepPsig": step,
            "bubbleF": bubble,
            "dewF": dew,
        }
    )

out = os.path.join(os.path.dirname(__file__), "..", "app", "lib", "charge", "ptData.generated.ts")
with open(out, "w") as fh:
    fh.write("// GENERATED by scripts/generate-pt-data.py. Do not edit by hand.\n")
    fh.write(f"// Source: CoolProp {CoolProp.__version__} (HEOS equations of state). Generated {date.today().isoformat()}.\n")
    fh.write("// Sea-level gauge pressure (14.696 psia atmosphere). Provisional until approved against a manufacturer chart.\n")
    fh.write("export const PT_GENERATED_SOURCE = " + json.dumps(f"CoolProp {CoolProp.__version__}") + ";\n")
    fh.write("export const PT_GENERATED_ON = " + json.dumps(date.today().isoformat()) + ";\n")
    fh.write("export const PT_GENERATED_TABLES = " + json.dumps(tables, separators=(",", ":")) + " as const;\n")
print("wrote", out, [(t["id"], len(t["dewF"])) for t in tables])
for t in tables:
    i = 80 // t["stepPsig"] * 0  # placeholder to keep loop simple
    psig = 100
    idx = psig // t["stepPsig"]
    print(t["id"], psig, "psig -> bubble", t["bubbleF"][idx], "dew", t["dewF"][idx])
