import { PT_GENERATED_ON, PT_GENERATED_SOURCE, PT_GENERATED_TABLES } from "./ptData.generated";

/**
 * Pressure-temperature data is generated by scripts/generate-pt-data.py, never typed by hand.
 * It stays PROVISIONAL until someone compares it with the manufacturer chart you trust
 * and flips this flag. While false, the charge tool shows a visible provisional notice.
 */
export const PT_DATA_APPROVED = false;
export const PT_DATA_SOURCE = `${PT_GENERATED_SOURCE}, generated ${PT_GENERATED_ON}`;

export type PtTable = {
  id: string;
  safetyClass: string;
  startPsig: number;
  stepPsig: number;
  /** Bubble point (saturated liquid) temperature in F at each pressure step. */
  bubbleF: readonly number[];
  /** Dew point (saturated vapor) temperature in F at each pressure step. */
  dewF: readonly number[];
};

export const PT_TABLES: readonly PtTable[] = PT_GENERATED_TABLES as unknown as readonly PtTable[];

export type SatResult = { ok: true; tempF: number } | { ok: false; error: string };

export function ptRefrigerants(tables: readonly PtTable[] = PT_TABLES) {
  return tables.map((t) => ({ id: t.id, safetyClass: t.safetyClass }));
}

export function maxPsig(table: PtTable): number {
  return table.startPsig + (table.dewF.length - 1) * table.stepPsig;
}

/**
 * Linear interpolation. Pressures outside the table are an error, never extrapolated.
 * Superheat uses the dew point column and subcooling uses the bubble point column.
 */
export function saturationTempF(refrigerantId: string, psig: number, kind: "dew" | "bubble", tables: readonly PtTable[] = PT_TABLES): SatResult {
  const table = tables.find((t) => t.id === refrigerantId);
  if (!table) return { ok: false, error: `No pressure-temperature data for ${refrigerantId}.` };
  if (!Number.isFinite(psig)) return { ok: false, error: "Pressure must be a number." };
  const top = maxPsig(table);
  if (psig < table.startPsig || psig > top) {
    return { ok: false, error: `${psig} psig is outside the ${refrigerantId} table (${table.startPsig} to ${top} psig). Check the gauge reading.` };
  }
  const column = kind === "dew" ? table.dewF : table.bubbleF;
  const position = (psig - table.startPsig) / table.stepPsig;
  const lower = Math.floor(position);
  const upper = Math.min(lower + 1, column.length - 1);
  const fraction = position - lower;
  return { ok: true, tempF: column[lower] + (column[upper] - column[lower]) * fraction };
}
